[package]
name = "starklytics_bounty"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
starknet = "2.4.0"